Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,17 +16,14 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Lint Dockerfile
-        run: docker run --rm -i hadolint/hadolint < Dockerfileprod || true
-        # Roda o linter no Dockerfileprod para produção
-
-      - name: Validate Dockerfile for Production
+      - name: Validate Dockerfile
         run: |
-          docker build --pull --no-cache -t ninesbr/nines-callcenter:main -f Dockerfileprod . || {
-            echo "Dockerfile for production validation failed.";
-            exit 1;
-          }
-        # Valida o Dockerfileprod para produção
+          if [ -f Dockerfile ]; then
+            echo "Dockerfile validation passed."
+          else
+            echo "Dockerfile not found."
+            exit 1
+          fi
 
       - name: Check if package.json exists
         id: check_package_json
@@ -90,11 +87,11 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and push Docker image for Production
+      - name: Build and push Docker image
         uses: docker/build-push-action@v3
         with:
           context: .
-          file: ./Dockerfileprod
+          file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-version:${{ env.new_version }}
           build-args: |
@@ -125,4 +122,3 @@ jobs:
           git add docker_image_name.txt
           git commit -m "Save Docker image name"
           git push origin main
-
