testando..5

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,21 +21,67 @@ jobs:
           docker run --rm -i hadolint/hadolint < Dockerfile || true
 
       - name: Validate Dockerfile
-        run: |
-          docker build --pull --no-cache -t ninesbr/nines-callcenter:main -f Dockerfile.base . || {
-            echo "Dockerfile validation failed due to circular dependency or other issues.";
+        run: docker build --pull --no-cache -t ninesbr/nines-callcenter:main -f Dockerfile . || {
+            echo "Dockerfile validation failed.";
             exit 1;
           }
 
-      - name: Build production stage
-        run: docker build --target production --pull --no-cache -t ninesbr/nines-callcenter:production -f Dockerfile.production .
-
-      # Add additional steps for building other stages if necessary
-
-      - name: Tag and push the final image
+      - name: Determine version
+        id: determine_version
         run: |
-          docker tag ninesbr/nines-callcenter:production ${{ secrets.DOCKER_USERNAME }}/ci-cd-version:${{ env.new_version }}
-          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-version:${{ env.new_version }}
+          if [ -f last_successful_version.txt ]; then
+            latest_version=$(cat last_successful_version.txt)
+          else
+            latest_version="v0.0.0"
+          fi
+          IFS='.' read -r major minor patch <<< "${latest_version#v}"
+
+          latest_commit_message=$(git log -1 --pretty=%B)
+          if [[ "$latest_commit_message" == *"BREAKING CHANGE"* ]]; then
+            increment="major"
+          elif [[ "$latest_commit_message" == *"feature"* ]]; then
+            increment="minor"
+          else
+            increment="patch"
+          fi
+
+          case $increment in
+            major)
+              new_version="v$(($major + 1)).0.0"
+              ;;
+            minor)
+              new_version="v$major.$(($minor + 1)).0"
+              ;;
+            patch)
+              new_version="v$major.$minor.$(($patch + 1))"
+              ;;
+          esac
+          echo "new_version=$new_version" >> $GITHUB_ENV
+          echo "new_version=$new_version"
+
+      - name: Create new tag
+        if: env.new_version != 'v0.0.0'
+        run: |
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+          git tag ${{ env.new_version }}
+          git push origin ${{ env.new_version }}
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v3
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-version:${{ env.new_version }}
+          build-args: |
+              version=${{ env.new_version }}
 
       - name: Store last successful version
         if: always()
