testando..6

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,14 +17,31 @@ jobs:
         uses: docker/setup-buildx-action@v1
 
       - name: Lint Dockerfile
-        run: |
-          docker run --rm -i hadolint/hadolint < Dockerfile || true
+        run: docker run --rm -i hadolint/hadolint < Dockerfileprod || true
+        # Roda o linter no Dockerfileprod para produção
 
-      - name: Validate Dockerfile
-        run: docker build --pull --no-cache -t ninesbr/nines-callcenter:main -f Dockerfile . || {
-            echo "Dockerfile validation failed.";
+      - name: Validate Dockerfile for Production
+        run: |
+          docker build --pull --no-cache -t ninesbr/nines-callcenter:main -f Dockerfileprod . || {
+            echo "Dockerfile for production validation failed.";
             exit 1;
           }
+        # Valida o Dockerfileprod para produção
+
+      - name: Check if package.json exists
+        id: check_package_json
+        run: |
+          if [ -f "package.json" ]; then
+            echo "package_json_exist=true" >> $GITHUB_ENV
+          else
+            echo "package_json_exist=false" >> $GITHUB_ENV
+          fi
+
+      - name: Run tests and install dependencies
+        if: env.package_json_exist == 'true'
+        run: |
+          npm install
+          npm test
 
       - name: Determine version
         id: determine_version
@@ -73,11 +90,11 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and push Docker image
+      - name: Build and push Docker image for Production
         uses: docker/build-push-action@v3
         with:
           context: .
-          file: ./Dockerfile
+          file: ./Dockerfileprod
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-version:${{ env.new_version }}
           build-args: |
